#Puerto del servicio
server.port=8070

#Mongo
spring.data.mongodb.uri=mongodb://localhost:27017/bootcamp58-entregable1

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id:${spring.application.name}:${spring.application.instance_id:${random.value}}

nombre.clente-persona=Demo1